name: Unit tests

on:
  push:
    paths:
      - '.github/workflows/pytest.yml'
      - 'src/**'
      - 'test/**'

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker.pkg.github.com/kamko/lnu_ht19_4me310_assignment2/ml-base

    steps:
    - uses: actions/checkout@v1
    - name: Install pytest
      run: pip install pytest
    - name: Run pytest
      run: pytest
