name: Unit tests

on:
  push:
    paths:
      - '.github/workflows/pytest.yml'
      - 'src/**'
      - 'test/**'

jobs:
  build:

    runs-on: ubuntu-latest
    container: kamko/ml-base

    steps:
      - uses: actions/checkout@v1
      - name: Run pytest
        run: pytest
